# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5998681bec035078fff9a6e892083d7e7e449d1c3589940468eb8e7781ae639283e3cd6381ea8f029276ad4cf6db4bea81e0c71a18c3421e2665cdc13c0e6e59

test:
  secret_key_base: 56acda96363cb87c6f52c769d4cf328b6ead7aaa8b2846fb02b00eece9c1dac02dbf8c904319d80177bcfb37b81163283239fa6656fa156fd9acd48475125c08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
